import type {
  DurationSeconds,
  IsoDateTime,
  PhoneNumber,
} from "./common.js";
import { isFiniteNumber, isIsoDateTime, isNonEmptyString, isRecord } from "./common.js";
import type {
  CallDirection,
  CallDisposition,
  CallLogId,
  CallRecordingId,
} from "./calls.js";
import type {
  DeviceId,
  DevicePermissions,
  DeviceSyncState,
  EmployeeId,
  EmployeeDevice,
  SimCardId,
} from "./employees.js";
import { isDevicePermissions } from "./employees.js";
import type { OrganizationId } from "./organizations.js";

export type SyncSchemaVersion = 1;
export type SyncItemOutcome = "created" | "updated" | "duplicate" | "rejected";
export type MobileCollectionMode = "android_call_log" | "synthetic_demo";
export const MOBILE_SYNC_MAX_ITEMS = 100;

/** Legacy wire shape retained for source compatibility. New provisioning responses never contain a token. */
export interface OpaqueDeviceCredential {
  tokenType: "Bearer";
  token: string;
  expiresAt: IsoDateTime;
}

export interface DeviceCredentialDescriptor {
  tokenType: "Bearer";
  expiresAt: IsoDateTime;
}

export interface MobilePolicyReference {
  id: string;
  contentHash: string;
}

/**
 * Server-authoritative collection policy. `contentHash` is an opaque canonical
 * server digest: clients compare it for equality but do not recompute it from
 * the presentation fields.
 */
export interface MobileCollectionPolicy extends MobilePolicyReference {
  policyVersion: string;
  disclosureVersion: string;
  collectionMode: MobileCollectionMode;
  purpose: "call_metadata";
  title: string;
  summary: string;
  disclosures: string[];
  effectiveAt: IsoDateTime;
}

export interface DevicePairingRedemptionInput {
  requestId: string;
  proposedBootstrapCredential: string;
}

export interface DevicePairingRedemptionResult {
  device: EmployeeDevice;
  pairing: {
    id: string;
    consumedAt: IsoDateTime;
  };
  bootstrapCredential: DeviceCredentialDescriptor;
}

export interface MobileConsentReceiptInput {
  acceptedAt: IsoDateTime;
  purpose: "call_metadata";
  locale?: string;
}

export interface MobileActivationInput {
  requestId: string;
  proposedSessionCredential: string;
  policy: MobilePolicyReference;
  consent: MobileConsentReceiptInput;
  permissions: DevicePermissions;
}

export interface MobileActivationResult {
  device: EmployeeDevice;
  sessionCredential: DeviceCredentialDescriptor;
  policy: MobilePolicyReference;
}

export interface MobileReconsentInput {
  requestId: string;
  policy: MobilePolicyReference;
  consent: MobileConsentReceiptInput;
  permissions: DevicePermissions;
}

export interface MobileReconsentResult {
  device: EmployeeDevice;
  policy: MobilePolicyReference;
  consentedAt: IsoDateTime;
}

export interface MobileSessionRotationPrepareInput {
  requestId: string;
  proposedSessionCredential: string;
}

export interface MobileSessionRotationPrepareResult {
  requestId: string;
  pendingCredential: DeviceCredentialDescriptor;
  preparedAt: IsoDateTime;
}

export interface MobileSessionRotationConfirmInput {
  requestId: string;
  prepareRequestId: string;
}

export interface MobileSessionRotationConfirmResult {
  requestId: string;
  credential: DeviceCredentialDescriptor;
  activatedAt: IsoDateTime;
}

export interface MobileSessionRevocationInput {
  requestId: string;
}

export interface MobileSessionRevocationResult {
  deviceId: DeviceId;
  revokedAt: IsoDateTime;
  consentWithdrawnAt: IsoDateTime;
}

/** Mobile representation of a native call-log row before it receives a server ID. */
export interface CallLogSyncItem {
  /** Stable local identifier generated by the app and reused on every retry. */
  localId: string;
  nativeCallId?: string;
  simCardId?: SimCardId;
  phoneNumber: PhoneNumber;
  contactName?: string;
  direction: CallDirection;
  disposition: CallDisposition;
  startedAt: IsoDateTime;
  answeredAt?: IsoDateTime;
  endedAt?: IsoDateTime;
  durationSeconds: DurationSeconds;
  ringDurationSeconds?: DurationSeconds;
  isInternal?: boolean;
  nativeLastModifiedAt?: IsoDateTime;
  recordingLocalId?: string;
}

/** Idempotent, bounded batch sent by the Android collector. */
export interface CallLogSyncBatch {
  schemaVersion: SyncSchemaVersion;
  collectionMode: MobileCollectionMode;
  batchId: string;
  organizationId: OrganizationId;
  employeeId: EmployeeId;
  deviceId: DeviceId;
  sentAt: IsoDateTime;
  previousCursor?: string;
  items: CallLogSyncItem[];
}

export interface CallLogSyncItemResult {
  localId: string;
  outcome: SyncItemOutcome;
  callLogId?: CallLogId;
  code?: string;
  message?: string;
  retryable?: boolean;
}

export interface CallLogSyncResult {
  batchId: string;
  acceptedAt: IsoDateTime;
  nextCursor: string;
  items: CallLogSyncItemResult[];
  serverTime: IsoDateTime;
}

export interface RecordingUploadManifest {
  localId: string;
  deviceId: DeviceId;
  callLocalId?: string;
  callLogId?: CallLogId;
  fileName: string;
  mimeType: string;
  sizeBytes: number;
  durationSeconds?: DurationSeconds;
  checksumSha256: string;
  capturedAt: IsoDateTime;
}

export interface RecordingUploadSession {
  uploadId: string;
  recordingId: CallRecordingId;
  chunkSizeBytes: number;
  expiresAt: IsoDateTime;
  uploadedPartNumbers: number[];
}

export interface RecordingUploadPart {
  uploadId: string;
  partNumber: number;
  byteLength: number;
  checksumSha256: string;
}

export interface CompleteRecordingUploadInput {
  uploadId: string;
  checksumSha256: string;
  parts: Array<{ partNumber: number; etag: string }>;
}

export interface DeviceHeartbeat {
  schemaVersion: SyncSchemaVersion;
  organizationId: OrganizationId;
  employeeId: EmployeeId;
  deviceId: DeviceId;
  observedAt: IsoDateTime;
  appVersion: string;
  osVersion: string;
  batteryPercent?: number;
  isCharging?: boolean;
  networkType?: "offline" | "wifi" | "cellular" | "ethernet" | "unknown";
  pendingCallCount: number;
  pendingRecordingCount: number;
  syncState: DeviceSyncState;
  permissions: DevicePermissions;
}

export type MobileDirective =
  | { type: "sync_now"; reason?: string }
  | { type: "refresh_configuration" }
  | { type: "consent_required"; policyId: string; contentHash: string; reason: string }
  | { type: "update_required"; minimumVersion: string; storeUrl: string }
  | { type: "pause_recording_uploads"; until?: IsoDateTime; reason: string }
  | { type: "device_revoked"; reason: string };

export interface HeartbeatAcknowledgement {
  serverTime: IsoDateTime;
  nextHeartbeatAfterSeconds: number;
  directives: MobileDirective[];
}

export interface MobileSyncError {
  localId?: string;
  occurredAt: IsoDateTime;
  operation: "call_log_read" | "call_sync" | "recording_discovery" | "recording_upload" | "heartbeat";
  code: string;
  message: string;
  retryable: boolean;
  attempt: number;
}

export interface MobileSyncDiagnostics {
  schemaVersion: SyncSchemaVersion;
  deviceId: DeviceId;
  generatedAt: IsoDateTime;
  cursor?: string;
  lastSuccessfulSyncAt?: IsoDateTime;
  recentErrors: MobileSyncError[];
}

export function isCallLogSyncItem(value: unknown): value is CallLogSyncItem {
  return (
    isRecord(value) &&
    isBoundedString(value.localId, 160) &&
    typeof value.phoneNumber === "string" && /^\+[1-9]\d{7,14}$/.test(value.phoneNumber) &&
    (value.direction === "incoming" || value.direction === "outgoing") &&
    ["answered", "missed", "rejected", "busy", "blocked", "voicemail", "unknown"].includes(
      value.disposition as CallDisposition,
    ) &&
    isExplicitIsoDateTime(value.startedAt) &&
    isBoundedInteger(value.durationSeconds, 0, 7 * 86_400) &&
    isOptionalBoundedString(value.nativeCallId, 160) &&
    isOptionalBoundedString(value.simCardId, 160) &&
    isOptionalBoundedString(value.contactName, 160) &&
    isOptionalExplicitIsoDateTime(value.answeredAt) &&
    isOptionalExplicitIsoDateTime(value.endedAt) &&
    isOptionalBoundedInteger(value.ringDurationSeconds, 0, 86_400) &&
    (value.isInternal === undefined || typeof value.isInternal === "boolean") &&
    isOptionalExplicitIsoDateTime(value.nativeLastModifiedAt) &&
    isOptionalBoundedString(value.recordingLocalId, 160) &&
    (value.answeredAt === undefined || (typeof value.answeredAt === "string" && value.answeredAt >= value.startedAt)) &&
    (value.endedAt === undefined || (typeof value.endedAt === "string" &&
      value.endedAt >= (typeof value.answeredAt === "string" ? value.answeredAt : value.startedAt)))
  );
}

export function isCallLogSyncBatch(value: unknown): value is CallLogSyncBatch {
  return (
    isRecord(value) &&
    value.schemaVersion === 1 &&
    (value.collectionMode === "android_call_log" || value.collectionMode === "synthetic_demo") &&
    isBoundedString(value.batchId, 160) &&
    isBoundedString(value.organizationId, 160) &&
    isBoundedString(value.employeeId, 160) &&
    isBoundedString(value.deviceId, 160) &&
    isExplicitIsoDateTime(value.sentAt) &&
    isOptionalBoundedString(value.previousCursor, 2048) &&
    Array.isArray(value.items) &&
    value.items.length <= MOBILE_SYNC_MAX_ITEMS &&
    value.items.every(isCallLogSyncItem)
  );
}

export function isMobileActivationInput(value: unknown): value is MobileActivationInput {
  if (!isRecord(value) || !isRecord(value.policy) || !isRecord(value.consent)) return false;
  return (
    isRequestId(value.requestId) &&
    isProposedDeviceCredential(value.proposedSessionCredential, "session") &&
    isMobilePolicyReference(value.policy) &&
    isExplicitIsoDateTime(value.consent.acceptedAt) &&
    value.consent.purpose === "call_metadata" &&
    isOptionalBoundedString(value.consent.locale, 35) &&
    isDevicePermissions(value.permissions)
  );
}

export function isMobileReconsentInput(value: unknown): value is MobileReconsentInput {
  if (!isRecord(value) || !isRecord(value.policy) || !isRecord(value.consent)) return false;
  return (
    isRequestId(value.requestId) &&
    isMobilePolicyReference(value.policy) &&
    isExplicitIsoDateTime(value.consent.acceptedAt) &&
    value.consent.purpose === "call_metadata" &&
    isOptionalBoundedString(value.consent.locale, 35) &&
    isDevicePermissions(value.permissions)
  );
}

export function isMobileSessionRotationPrepareInput(value: unknown): value is MobileSessionRotationPrepareInput {
  return (
    isRecord(value) &&
    isRequestId(value.requestId) &&
    isProposedDeviceCredential(value.proposedSessionCredential, "session")
  );
}

export function isMobileSessionRotationConfirmInput(value: unknown): value is MobileSessionRotationConfirmInput {
  return isRecord(value) && isRequestId(value.requestId) && isRequestId(value.prepareRequestId) &&
    value.requestId !== value.prepareRequestId;
}

export function isMobileSessionRevocationInput(value: unknown): value is MobileSessionRevocationInput {
  return isRecord(value) && isRequestId(value.requestId);
}

export function isMobilePolicyReference(value: unknown): value is MobilePolicyReference {
  return (
    isRecord(value) &&
    isRequestId(value.id) &&
    typeof value.contentHash === "string" &&
    /^[0-9a-f]{64}$/.test(value.contentHash)
  );
}

export function isMobileCollectionMode(value: unknown): value is MobileCollectionMode {
  return value === "android_call_log" || value === "synthetic_demo";
}

export function isRequestId(value: unknown): value is string {
  return typeof value === "string" &&
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
}

export function isProposedDeviceCredential(
  value: unknown,
  credentialType: "bootstrap" | "session",
): value is string {
  if (typeof value !== "string") return false;
  const prefix = credentialType === "bootstrap" ? "clb" : "cls";
  return new RegExp(`^${prefix}_[A-Za-z0-9_-]{43}$`).test(value);
}

export function isDeviceHeartbeat(value: unknown): value is DeviceHeartbeat {
  return (
    isRecord(value) &&
    value.schemaVersion === 1 &&
    isBoundedString(value.organizationId, 160) &&
    isBoundedString(value.employeeId, 160) &&
    isBoundedString(value.deviceId, 160) &&
    isExplicitIsoDateTime(value.observedAt) &&
    isBoundedString(value.appVersion, 50) &&
    isBoundedString(value.osVersion, 50) &&
    isOptionalBoundedInteger(value.batteryPercent, 0, 100) &&
    (value.isCharging === undefined || typeof value.isCharging === "boolean") &&
    (value.networkType === undefined || ["offline", "wifi", "cellular", "ethernet", "unknown"].includes(value.networkType as string)) &&
    isBoundedInteger(value.pendingCallCount, 0, 1_000_000) &&
    isBoundedInteger(value.pendingRecordingCount, 0, 1_000_000) &&
    ["never_synced", "idle", "syncing", "degraded", "failed"].includes(value.syncState as string) &&
    isDevicePermissions(value.permissions)
  );
}

function isBoundedString(value: unknown, maximumLength: number): value is string {
  return isNonEmptyString(value) && value.trim().length <= maximumLength;
}

function isOptionalBoundedString(value: unknown, maximumLength: number): boolean {
  return value === undefined || isBoundedString(value, maximumLength);
}

function isExplicitIsoDateTime(value: unknown): value is IsoDateTime {
  return isIsoDateTime(value) && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?(?:Z|[+-]\d{2}:\d{2})$/.test(value);
}

function isOptionalExplicitIsoDateTime(value: unknown): boolean {
  return value === undefined || isExplicitIsoDateTime(value);
}

function isBoundedInteger(value: unknown, minimum: number, maximum: number): value is number {
  return Number.isSafeInteger(value) && (value as number) >= minimum && (value as number) <= maximum;
}

function isOptionalBoundedInteger(value: unknown, minimum: number, maximum: number): boolean {
  return value === undefined || isBoundedInteger(value, minimum, maximum);
}

export function isRecordingUploadManifest(value: unknown): value is RecordingUploadManifest {
  return (
    isRecord(value) &&
    isNonEmptyString(value.localId) &&
    isNonEmptyString(value.deviceId) &&
    isNonEmptyString(value.fileName) &&
    isNonEmptyString(value.mimeType) &&
    isFiniteNumber(value.sizeBytes) &&
    value.sizeBytes >= 0 &&
    isNonEmptyString(value.checksumSha256) &&
    isIsoDateTime(value.capturedAt)
  );
}
