import { createHash, randomBytes, randomUUID } from "node:crypto";

const sha256 = (body: Uint8Array) => createHash("sha256").update(body).digest("hex");
export interface RecordingPolicy { enabled: boolean; disclosuresAccepted: boolean; quotaBytes: number; retentionDays: number; transcriptionEnabled: boolean; }
export interface RecordingManifest { callLogId: string; fileName: string; mimeType: "audio/mpeg" | "audio/mp4" | "audio/wav" | "audio/ogg"; sizeBytes: number; checksumSha256: string; source: "device_folder" | "voip_provider" | "manual_upload"; }
export interface RecordingObjectStore { put(key: string, body: Uint8Array): Promise<void>; get(key: string): Promise<Uint8Array | undefined>; delete(key: string): Promise<void>; }
export interface TranscriptionProvider { transcribe(input: { recordingId: string; audio: Uint8Array; mimeType: string }): Promise<{ language: string; text: string }>; }
interface Session { id: string; organizationId: string; recordingId: string; manifest: RecordingManifest; parts: Map<number, Uint8Array>; expiresAt: number; }
interface Recording { id: string; organizationId: string; manifest: RecordingManifest; status: "uploading" | "available" | "deleted"; objectKey?: string; transcriptionStatus: "not_requested" | "queued" | "processing" | "complete" | "failed"; transcript?: { language: string; text: string }; }

export class InMemoryRecordingObjectStore implements RecordingObjectStore {
  readonly objects = new Map<string, Uint8Array>(); async put(key: string, body: Uint8Array) { this.objects.set(key, new Uint8Array(body)); } async get(key: string) { const value = this.objects.get(key); return value && new Uint8Array(value); } async delete(key: string) { this.objects.delete(key); }
}

/** Phase 6 orchestration. Persistent deployments replace its metadata repository while preserving these invariants. */
export class RecordingService {
  private readonly policies = new Map<string, RecordingPolicy>(); private readonly sessions = new Map<string, Session>(); private readonly recordings = new Map<string, Recording>(); private readonly checksumIndex = new Map<string, string>(); private readonly grants = new Map<string, { organizationId: string; recordingId: string; expiresAt: number }>();
  constructor(private readonly store: RecordingObjectStore, private readonly transcriber?: TranscriptionProvider, private readonly now = () => Date.now()) {}
  setPolicy(organizationId: string, policy: RecordingPolicy): void { if (policy.quotaBytes < 1 || policy.retentionDays < 1) throw new Error("Invalid recording policy"); this.policies.set(organizationId, { ...policy }); }
  begin(organizationId: string, manifest: RecordingManifest): { uploadId: string; recordingId: string; chunkSizeBytes: number; expiresAt: string; deduplicated: boolean } {
    const policy = this.policies.get(organizationId); if (!policy?.enabled) throw new Error("Recording uploads are disabled for this organization"); if (!policy.disclosuresAccepted) throw new Error("Recording disclosure and consent are required"); if (!/^[a-f0-9]{64}$/.test(manifest.checksumSha256)) throw new Error("Invalid SHA-256 checksum"); if (manifest.sizeBytes < 1 || manifest.sizeBytes > Math.min(policy.quotaBytes, 500 * 1024 * 1024)) throw new Error("Recording exceeds the organization quota");
    const duplicate = this.checksumIndex.get(`${organizationId}:${manifest.checksumSha256}`); if (duplicate) return { uploadId: "deduplicated", recordingId: duplicate, chunkSizeBytes: 5 * 1024 * 1024, expiresAt: new Date(this.now()).toISOString(), deduplicated: true };
    const recordingId = randomUUID(); const uploadId = randomUUID(); const expiresAt = this.now() + 60 * 60 * 1000; this.recordings.set(recordingId, { id: recordingId, organizationId, manifest: { ...manifest }, status: "uploading", transcriptionStatus: "not_requested" }); this.sessions.set(uploadId, { id: uploadId, organizationId, recordingId, manifest: { ...manifest }, parts: new Map(), expiresAt }); return { uploadId, recordingId, chunkSizeBytes: 5 * 1024 * 1024, expiresAt: new Date(expiresAt).toISOString(), deduplicated: false };
  }
  uploadPart(organizationId: string, uploadId: string, partNumber: number, body: Uint8Array, checksum: string): void {
    const session = this.sessions.get(uploadId); if (!session || session.organizationId !== organizationId || session.expiresAt <= this.now()) throw new Error("Upload session is unavailable or expired"); if (!Number.isInteger(partNumber) || partNumber < 1 || partNumber > 10_000 || body.length > 5 * 1024 * 1024) throw new Error("Invalid recording part"); if (sha256(body) !== checksum) throw new Error("Recording part checksum mismatch"); session.parts.set(partNumber, new Uint8Array(body));
  }
  async complete(organizationId: string, uploadId: string): Promise<{ recordingId: string; status: "available" }> {
    const session = this.sessions.get(uploadId); if (!session || session.organizationId !== organizationId || session.expiresAt <= this.now()) throw new Error("Upload session is unavailable or expired"); const partNumbers = [...session.parts.keys()].sort((a, b) => a - b); if (partNumbers.some((value, index) => value !== index + 1)) throw new Error("Recording parts must be contiguous"); const body = Buffer.concat(partNumbers.map((part) => session.parts.get(part)!)); if (body.length !== session.manifest.sizeBytes || sha256(body) !== session.manifest.checksumSha256) throw new Error("Completed recording checksum or size mismatch");
    const key = `${organizationId}/recordings/${session.recordingId}`; await this.store.put(key, body); const recording = this.recordings.get(session.recordingId)!; recording.status = "available"; recording.objectKey = key; this.checksumIndex.set(`${organizationId}:${session.manifest.checksumSha256}`, recording.id); this.sessions.delete(uploadId); const policy = this.policies.get(organizationId)!; if (policy.transcriptionEnabled && this.transcriber) recording.transcriptionStatus = "queued"; return { recordingId: recording.id, status: "available" };
  }
  issuePlaybackGrant(organizationId: string, recordingId: string): { token: string; expiresAt: string } { const recording = this.recordings.get(recordingId); if (!recording || recording.organizationId !== organizationId || recording.status !== "available") throw new Error("Recording is unavailable"); const token = `rec_${randomBytes(32).toString("base64url")}`; const expiresAt = this.now() + 5 * 60 * 1000; this.grants.set(sha256(Buffer.from(token)), { organizationId, recordingId, expiresAt }); return { token, expiresAt: new Date(expiresAt).toISOString() }; }
  async playback(organizationId: string, recordingId: string, token: string, range?: { start: number; end?: number }): Promise<{ body: Uint8Array; mimeType: string; totalBytes: number; start: number; end: number }> { const grant = this.grants.get(sha256(Buffer.from(token))); const recording = this.recordings.get(recordingId); if (!grant || grant.organizationId !== organizationId || grant.recordingId !== recordingId || grant.expiresAt <= this.now() || !recording?.objectKey) throw new Error("Playback grant is invalid or expired"); const body = await this.store.get(recording.objectKey); if (!body) throw new Error("Recording object is unavailable"); const start = range?.start ?? 0; const end = Math.min(range?.end ?? body.length - 1, body.length - 1); if (!Number.isInteger(start) || start < 0 || start > end) throw new Error("Invalid playback range"); return { body: body.slice(start, end + 1), mimeType: recording.manifest.mimeType, totalBytes: body.length, start, end }; }
  async processTranscription(recordingId: string): Promise<"complete" | "failed" | "idle"> { const recording = this.recordings.get(recordingId); if (!recording || recording.transcriptionStatus !== "queued" || !recording.objectKey || !this.transcriber) return "idle"; recording.transcriptionStatus = "processing"; try { const audio = await this.store.get(recording.objectKey); if (!audio) throw new Error("Recording object is unavailable"); recording.transcript = await this.transcriber.transcribe({ recordingId, audio, mimeType: recording.manifest.mimeType }); recording.transcriptionStatus = "complete"; return "complete"; } catch { recording.transcriptionStatus = "failed"; return "failed"; } }
  async delete(organizationId: string, recordingId: string): Promise<boolean> { const recording = this.recordings.get(recordingId); if (!recording || recording.organizationId !== organizationId || recording.status === "deleted") return false; if (recording.objectKey) await this.store.delete(recording.objectKey); recording.status = "deleted"; delete recording.objectKey; delete recording.transcript; this.checksumIndex.delete(`${organizationId}:${recording.manifest.checksumSha256}`); return true; }
  get(recordingId: string) { const recording = this.recordings.get(recordingId); return recording && { id: recording.id, status: recording.status, transcriptionStatus: recording.transcriptionStatus, transcript: recording.transcript }; }
}
